blog/urls.py
from django.contrib import admin
from django.urls import path 
from . import views
urlpatterns=[
    path('' , views.home , name='home'),
    path('about/', views.about , name='about'),
    path('contact/', views.contact , name='contact'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/' , views.user_logout , name='logout'),
    path('login/' , views.user_login , name='login'),
    path('signup/' , views.signup , name='signup'),
    path('addpost', views.addpost , name='addpost'),
    path('editpost/<int:id>' ,views.editpost , name='editpost'),
    path('deletepost/<int:id>',views.deletepost , name='deletepost'),
]

blogapp/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models

# Post models here.

class post(models.Model):
    title=models.CharField(max_length=170)
    desc=models.CharField(max_length=3000)

blog/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm ,UsernameField
from django.contrib.auth.models import User
from django.utils.translation import gettext ,gettext_lazy as _
from .models import post

# Sign Up Form
class signupForm(UserCreationForm):
    password1=forms.CharField(label='Password' ,widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2=forms.CharField(label='Confirm Password' ,widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model=User
        fields=['username' , 'first_name' , 'last_name' , 'email']
        label={'first_name':'First Name', 'last_name':'Last Name' , 'email':'Email'}
        widgets={
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'last_name':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
                }

# Login Form 

class loginform(AuthenticationForm):
    username=UsernameField(widget=forms.TextInput(attrs={'auto-focus':True , 'class':'form-control'}))
    password=forms.CharField(label=_("Password"), strip=False , widget=forms.PasswordInput(attrs={'autocomplete':'current-password' , 'class':'form-control'}))
    
    
# Post Form 

class postform(forms.ModelForm):
    class Meta:
        model=post
        fields=['title' , 'desc']
        label={
            'title':'Title',
            'desc':'Description',
        }
        widgets={
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'desc':forms.Textarea(attrs={'class':'form-control'}),
        }

blog/views.py
from django.shortcuts import render , HttpResponseRedirect
from .forms import signupForm  , loginform , postform
from .models import post
from django.contrib import messages
from django.contrib.auth import authenticate , login , logout
from django.contrib.auth.models import Group

# Home View
def home(request):
    posts=post.objects.all()
    return render(request, 'index.html' , {'posts':posts})
# signup view
def signup(request):
    if request.method=='POST':
        form=signupForm(request.POST)
        if form.is_valid():
            user=form.save()
            group=Group.objects.get(name='Author')
            user.groups.add(group)
            messages.success(request, 'Congratulations! Now you are an Author.')
    else:
        form=signupForm()
    return render(request, 'signup.html' , {'form':form})


# login view
def user_login(request):
    if not request.user.is_authenticated:
        if request.method=='POST':
            form=loginform(request=request , data=request.POST)
            if form.is_valid():
                uname=form.cleaned_data['username']
                upass=form.cleaned_data['password']
                user=authenticate(username=uname , password=upass)
                if user is not None:
                    login(request , user)
                    messages.success(request, 'You Are Logged In Succefully')
                    return HttpResponseRedirect('/dashboard/')
        else:
            form=loginform()
        return render(request, 'login.html' , {'form':form})
    else:
        return HttpResponseRedirect('/dashboard/')
    
# logout view
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/login')

# dashboard view
def dashboard(request):
    if request.user.is_authenticated:
        posts=post.objects.all()
        # user profile code
        user=request.user
        full_name=user.get_full_name()
        gps=user.groups.all()
        return render(request, 'dashboard.html' , {'posts':posts , 'full_name':full_name , 'groups':gps})
    else:
        return render(request, 'login.html')


 
# about View
def about(request):
    return render(request, 'about.html')

# Contact Page View 
def contact(request):
    return render(request, 'contact.html')

# ADD Post
def addpost(request):
    if request.user.is_authenticated:
        if request.method=='POST':
            form=postform(request.POST)
            if form.is_valid():
                title=form.cleaned_data['title']
                desc=form.cleaned_data['desc']
                pst=post(title=title , desc=desc)
                pst.save()
                form= postform()
                return HttpResponseRedirect('/dashboard/')
        else:
            form= postform()
            return render(request , 'addpost.html' , {'form':form})
    else:
        return render(request , 'login.html')

# Edit Post
def editpost(request , id):
    if request.user.is_authenticated:
        if request.method=='POST':
            pi=post.objects.get(pk=id)
            form=postform(request.POST, instance=pi)
            if form.is_valid():
                form.save()
            return HttpResponseRedirect('/dashboard/')
        else:
            pi=post.objects.get(pk=id)
            form=postform(instance=pi)
            return render(request , 'updatepost.html' , {'form':form})
    else:
        return render(request , 'login.html')

    
# Delete Post

def deletepost(request , id):
    if request.user.is_authenticated:
        if request.method=='POST':
            pi=post.objects.get(pk=id)
            pi.delete()
            return HttpResponseRedirect('/dashboard/')
    else:
        return render(request , 'login.html')

blog/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
 <div class="col-sm-10">
    <h3 class="text-white my-5">About Us</h3>


 <div class="jumbotron jumbotron-fluid pt-10 bg-dark">
   <h1 class="display-4 font-weight-bold text-white">About</h1>
   <p class="lead text-white pb-10 ">Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus quo aliquid facere dolor, reiciendis quidem sunt labore blanditiis unde. Dolores cum perferendis autem ratione sit aut quo ipsum nihil ad eligendi! Ex quos dolores provident amet nisi cumque assumenda architecto, temporibus expedita rerum omnis, laborum ea consequatur optio nulla fuga non doloribus minus, excepturi totam corrupti beatae? Exercitationem quam eos debitis sapiente facere amet. Minus possimus tempore odio repudiandae dolore sapiente. Temporibus quisquam animi aliquam ut fuga, nihil ipsa sint minus molestias culpa suscipit a natus libero quasi quod autem vero velit aperiam eaque nulla dolor. Molestias alias sed expedita, natus iure temporibus quasi! Velit ducimus consequuntur maiores tempore totam dignissimos sunt, voluptatum perspiciatis molestiae quisquam suscipit cum soluta enim reprehenderit doloremque quod obcaecati provident consectetur, culpa debitis eum amet. Cupiditate laudantium dolore excepturi odit beatae natus ratione dignissimos quod veniam obcaecati ea neque, itaque molestias temporibus omnis optio! Maiores corrupti aliquam quia illo, ex cum delectus incidunt. Culpa nisi quo qui laudantium? Magni unde, fugit minima at repellat eius impedit officiis eaque reprehenderit dignissimos pariatur officia fuga aperiam, doloremque natus cupiditate odit amet tenetur distinctio maxime libero adipisci eos assumenda! Dolores, ducimus eaque. Quod quasi sint ducimus aliquam. Sint!</p>
 
 </div>
{% endblock content%}

blog/templates/addpost.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Add Post</h3>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        
            {{form.as_p}}
        <input type="submit" name="" id="" class="btn btn-primary" style="margin-top: 10px;" value="ADD">
        <a href="{% url 'dashboard' %}" class="btn btn-danger">Cancel</a>
        </form>
</div>

{% endblock %}

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog App</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body style="background-color: #454545;">
     <div class="container-fluid bg-dark">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand my-1" href="{% url 'home' %}">MyBlog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'home' %}">Home </a>
                <a class="nav-item nav-link" href="{% url 'about' %}">About</a>
                <a class="nav-item nav-link" href="{% url 'contact' %}">Contact</a>
                {% if request.user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'dashboard' %}">DashBoard</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">LogOut</a>
                {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'signup' %}">Sign Up</a>

                {% endif %}

            </div>
            </div>
          </nav>
    </div>

     <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% block msg %}
                {% endblock msg %}
            </div>
        </div>

        <div class="row">
            {% block side %}
            {% endblock side %}
    
            {% block content %}
            {% endblock content %}
        </div>
     </div>
    </div>


     <!-- FOOTER -->
     
     <!-- <footer class="text-center text-white" style="background-color: grey; position:relative;">
        <div class="footer12" style="position: absolute; width:100%; bottom:0px;"></div>
     
        <div class="text-center text-dark p-3" style="background-color: rgba(202, 182, 182, 0.2);">
          © 2023 Copyright:
          <a class="text-dark" href="{% url 'home' %}">MyBlog.com</a>
        </div>
          </div>
      </footer> -->
  
     
    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
    <!-- popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>


</body>
</html>

blog/templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
 <div class="col-sm-10">
    <h3 class="text-white my-5">Contact Us</h3>

    <!--Section: Contact v.2-->
<section class="mb-4">

    <!--Section heading-->

    <div class="row mb-20">

        <!--Grid column-->
        <div class="col-md-9 mb-md-0 mb-5">
            <form id="contact-form" name="contact-form" action="mail.php" method="POST">

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="name" name="name" class="form-control">
                            <label for="name" class="text-white">Your name</label>
                        </div>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="email" name="email" class="form-control ">
                            <label for="email" class="text-white">Your email</label>
                        </div>
                    </div>
                    <!--Grid column-->

                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0">
                            <input type="text" id="subject" name="subject" class="form-control ">
                            <label for="subject" class="text-white">Subject</label>
                        </div>
                    </div>
                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-12">

                        <div class="md-form">
                            <textarea type="text" id="message" name="message" rows="2" class="form-control md-textarea "></textarea>
                            <label for="message" class="text-white">Your message</label>
                        </div>

                    </div>
                </div>
                <!--Grid row-->

            </form>

            <div class="text-center text-md-left">
                <a class="btn btn-primary" onclick="document.getElementById('contact-form').submit();">Send</a>
            </div>
            <div class="status"></div>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-3 text-center">
            <ul class="list-unstyled mb-0">
                <li><i class="fas fa-map-marker-alt fa-2x text-white"></i>
                    <p class="text-white">Lahore Pakistan</p>
                </li>

                <li><i class="fas fa-phone mt-4 fa-2x text-white"></i>
                    <p class="text-white">+923476346528</p>
                </li>

                <li><i class="fas fa-envelope mt-4 fa-2x text-white"></i>
                    <p class="text-white">contact@MyBlog.com</p>
                </li>
            </ul>
        </div>
        <!--Grid column-->

    </div>

</section>
<!--Section: Contact v.2-->

{% endblock content%}

blog/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block side %}
<div class="col-sm-2">
    <h3 class="text-white my-5">User Profile</h3>
     <h4 class="text-center text-white">{{full_name}}</h4>
     {% for group in groups %}
     <p class="text-center text-white">{{group.name}}</p>
  {% endfor %}
 </div>

{% endblock side %}

{% block content %}



 <div class="col-sm-10">
    
    <!-- MESSAGES -->
    {% if messages %}
        {% for message in messages %}
        <p {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %}>{{message}}</p>
        {% endfor %}
    {% endif %}

    <h4 class="text-center alert alert-info mt-3">All Posts</h4>
    <a href="{% url 'addpost' %}" class="btn btn-success">Add Post</a>
    {% if posts %}
    <table class="hover bg-light mt-4 mb-20">
       <thead style="border-bottom: 1px solid black;">
        <tr class="text-center ">
            <th scope="col" style="width: 2%; padding: 10px 8px ;">Id</th>
            <th scope="col" style="width: 28%; padding: 10px 8px ;">Name</th>
            <th scope="col" style="width: 55%; padding: 10px 8px ;">Post</th>
            <th scope="col" style="width: 15%; padding: 10px 8px ;">Action</th>
        </tr>
       </thead>
       <tbody>
        {% for  post in posts %}
        <tr scope="row" style="border-bottom: 2px solid black;">
            <th style="padding: 10px 8px ;">{{post.id}}</th>
            <td style="padding: 10px 8px ;">{{post.title}}</td>
            <td style="padding: 10px 8px ;">{{post.desc}}</td>
            <td class="row">
                <div class="col-6" style="padding: 10px 8px ;">
                    <a href="{% url 'editpost' post.id %}" class="btn btn-warning btn-sm">Edit</a>
                </div>
                {% if perms.blog.delete_post %}
            <div class="col-6" style="padding: 10px 8px ;">
                <form action="{% url 'deletepost' post.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-danger btn-sm" value="delete" >
                </form>
            </div>
            {% endif %}
            </td>
        </tr>
    {% endfor %}
       </tbody>

    </table>
    {% endif %}




{% endblock content%}

blog/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
 <div class="col-sm-10">
    <h3 class="text-white my-5">Home Page</h3>

{% for post in posts  %}
 <div class="jumbotron jumbotron-fluid pt-10 bg-dark">
   <h1 class="display-4 font-weight-bold text-white">{{post.title}}</h1>
   <p class="lead text-white pb-10 ">{{post.desc}}</p>
 
 </div>
 {% endfor %}
{% endblock content%}

blog/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
 <div class="col-sm-10">
    <h3 class="text-white my-5">Login</h3>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        
            {{form.as_p}}
        <input type="submit" name="" id="" class="btn btn-primary" style="margin-top: 10px;" value="submit">
        </form>

{% endblock content%}

blog/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
 <div class="col-sm-10">
    <h3 class="text-white my-5">Become An Author</h3>

    <!-- MESSAGES -->
    {% if messages %}
        {% for message in messages %}
        <p {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %}>{{message}}</p>
        {% endfor %}
    {% endif %}

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {% for filed in form %}
           <div class="form-group">
            {{filed.label_tag}}{{filed}}{{filed.errors|striptags}}
        </div>
            {% endfor %}
            <input type="submit" name="" id="" class="btn btn-primary" style="margin-top: 10px;" value="submit">
            {% if form.non_field_errors %}
            {% for error in non_field_errors %} 
            <p> {{error}}</p>
            {% endfor %} 
            {% endif %} 
        </form>


{% endblock content%}

blog/templates/updatepost.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Add Post</h3>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        
            {{form.as_p}}
        <input type="submit" name="" id="" class="btn btn-primary" style="margin-top: 10px;" value="ADD">
        <a href="{% url 'dashboard' %}" class="btn btn-danger">Cancel</a>
        </form>
</div>

{% endblock %}